
const data = [
  {
    label: '01',
    value: '开发区(高桥街道)',
    children: [
      {value: '落晚村', label: '1A1'},
      {value: '楼下角村', label: '1A2'},
      {value: '高桥村', label: '1A3'},
      {value: '亭桥村', label: '1A4'},
      {value: '永安村', label: '1A5'},
      {value: '范桥村', label: '1A6'},
      {value: '毛水浜村', label: '1A7'},
      {value: '三村村', label: '1A8'},
      {value: '骑力村', label: '1A9'},
      {value: '湘庄村', label: '1A10'},
      {value: '龙南村', label: '1A11'},
      {value: '漕泾村', label: '1A12'},
      {value: '迎丰村', label: '1A13'},
      {value: '越丰村', label: '1A14'},
      {value: '新丰村', label: '1A15'},
      {value: '高桥社区', label: '1A16'},
    ],
  },
  {
    label: '02',
    value: '梧桐街道',
    children: [
      {value: '城东村', label: '2A1'},
      {value: '东方红村', label: '2A2'},
      {value: '庆丰村', label: '2A3'},
      {value: '三新村', label: '2A4'},
      {value: '民安村', label: '2A5'},
      {value: '城西村', label: '2A6'},
      {value: '钱林村', label: '2A7'},
      {value: '同心村', label: '2A8'},
      {value: '逾桥村', label: '2A9'},
      {value: '梧桐村', label: '2A10'},
      {value: '安乐村', label: '2A11'},
      {value: '百福村', label: '2A12'},
      {value: '新玄村', label: '2A13'},
      {value: '桃园村', label: '2A14'},
      {value: '革新村', label: '2A15'},
      {value: '城南村', label: '2A16'},
      {value: '众善村', label: '2A17'},
      {value: '庆丰社区', label: '2A18'},
      {value: '九曲社区', label: '2A19'},
      {value: '杨家门社区', label: '2A20'},
      {value: '东兴社区', label: '2A21'},
      {value: '学前社区', label: '2A22'},
      {value: '大发社区', label: '2A23'},
      {value: '文昌社区', label: '2A24'},
      {value: '凤鸣社区', label: '2A25'},
      {value: '永宁社区', label: '2A26'},
      {value: '环南社区', label: '2A27'},
      {value: '莲花社区', label: '2A28'},
      {value: '振东社区', label: '2A29'},
      {value: '百乐社区', label: '2A30'},
      {value: '凤凰社区', label: '2A31'},
      {value: '复兴社区', label: '2A32'},
      {value: '同庆社区', label: '2A33'},
    ],
  },
  {
    label: '03',
    value: '凤鸣街道',
    children: [
      {value: '史桥村', label: '3A1'},
      {value: '红旗村', label: '3A2'},
      {value: '路家园村', label: '3A3'},
      {value: '灵安村', label: '3A4'},
      {value: '环南村', label: '3A5'},
      {value: '西牛桥村', label: '3A6'},
      {value: '建胜村', label: '3A7'},
      {value: '合星村', label: '3A8'},
      {value: '中群村', label: '3A9'},
      {value: '联庄村', label: '3A10'},
      {value: '新农村村', label: '3A11'},
      {value: '长新村', label: '3A12'},
      {value: '桑园桥村', label: '3A13'},
      {value: '李家弄村', label: '3A14'},
      {value: '灵安社区', label: '3A15'},
    ],
  },
  {
    label: '04',
    value: '濮院镇',
    children: [
      {value: '新河村', label: '4A1'},
      {value: '永越村', label: '4A2'},
      {value: '永乐村', label: '4A3'},
      {value: '新濮村', label: '4A4'},
      {value: '新星村', label: '4A5'},
      {value: '永联村', label: '4A6'},
      {value: '新东村', label: '4A7'},
      {value: '新妙智村', label: '4A8'},
      {value: '新联村', label: '4A9'},
      {value: '新港村', label: '4A10'},
      {value: '红旗漾村', label: '4A11'},
      {value: '油车桥村', label: '4A12'},
      {value: '星旗村', label: '4A13'},
      {value: '永乐社区', label: '4A14'},
      {value: '梅园社区', label: '4A15'},
      {value: '双龙社区', label: '4A16'},
      {value: '锦苑社区', label: '4A17'},
      {value: '新生社区', label: '4A18'},
    ],
  },
  {
    label: '05',
    value: '屠甸镇',
    children: [
      {value: '联星村', label: '5A1'},
      {value: '红星村', label: '5A2'},
      {value: '荣星村', label: '5A3'},
      {value: '万星村', label: '5A4'},
      {value: '海星村', label: '5A5'},
      {value: '和平村', label: '5A6'},
      {value: '恒丰村', label: '5A7'},
      {value: '汇丰村', label: '5A8'},
      {value: '屠甸社区', label: '5A9'},
    ],
  },
  {
    label: '06',
    value: '崇福镇',
    children: [
      {value: '城郊村', label: '6A1'},
      {value: '上市村', label: '6A2'},
      {value: '东安村', label: '6A3'},
      {value: '民利村', label: '6A4'},
      {value: '湾里村村', label: '6A5'},
      {value: '留良村', label: '6A6'},
      {value: '新桥村', label: '6A7'},
      {value: '华光村', label: '6A8'},
      {value: '御驾桥村', label: '6A9'},
      {value: '南阳村', label: '6A10'},
      {value: '茅桥埭村', label: '6A11'},
      {value: '钱家埭村', label: '6A12'},
      {value: '李家浜村', label: '6A13'},
      {value: '陈家埭村', label: '6A14'},
      {value: '店街塘村', label: '6A15'},
      {value: '芦母村', label: '6A16'},
      {value: '景卫村', label: '6A17'},
      {value: '中夫村', label: '6A18'},
      {value: '李家坝村', label: '6A19'},
      {value: '联丰村', label: '6A20'},
      {value: '上莫村', label: '6A21'},
      {value: '新益村', label: '6A22'},
      {value: '利顺村', label: '6A23'},
      {value: '星火村', label: '6A24'},
      {value: '五丰村', label: '6A25'},
      {value: '芝村村', label: '6A26'},
      {value: '语溪社区', label: '6A27'},
      {value: '崇德社区', label: '6A28'},
      {value: '中山社区', label: '6A29'},
    ],
  },
  {
    label: '07',
    value: '洲泉镇',
    children: [
      {value: '马鸣村', label: '7A1'},
      {value: '众安村', label: '7A2'},
      {value: '义马村', label: '7A3'},
      {value: '湘溪村', label: '7A4'},
      {value: '晚村村', label: '7A5'},
      {value: '道村村', label: '7A6'},
      {value: '后塘村', label: '7A7'},
      {value: '夜明村', label: '7A8'},
      {value: '坝桥村', label: '7A9'},
      {value: '青石村', label: '7A10'},
      {value: '合兴村', label: '7A11'},
      {value: '金家浜村', label: '7A12'},
      {value: '清河村', label: '7A13'},
      {value: '东田村', label: '7A14'},
      {value: '小园头村', label: '7A15'},
      {value: '岑山村', label: '7A16'},
      {value: '南庄村', label: '7A17'},
      {value: '石山头村', label: '7A18'},
      {value: '屈家浜村', label: '7A19'},
      {value: '朝晖社区', label: '7A20'},
    ],
  },
  {
    label: '08',
    value: '大麻镇',
    children: [
      {value: '海华村', label: '8A1'},
      {value: '麻溪村', label: '8A2'},
      {value: '西南村', label: '8A3'},
      {value: '大庄村', label: '8A4'},
      {value: '湘漾村', label: '8A5'},
      {value: '百富村', label: '8A6'},
      {value: '崇益村', label: '8A7'},
      {value: '光明村', label: '8A8'},
      {value: '吉字浜村', label: '8A9'},
      {value: '永丰村', label: '8A10'},
      {value: '黎明村', label: '8A11'},
      {value: '大麻社区', label: '8A12'},
    ],
  },
  {
    label: '10',
    value: '河山镇',
    children: [
      {value: '八泉村', label: '10A1'},
      {value: '庙头村', label: '10A2'},
      {value: '堰头村', label: '10A3'},
      {value: '五泾村', label: '10A4'},
      {value: '王家弄村', label: '10A5'},
      {value: '河山村', label: '10A6'},
      {value: '石栏桥村', label: '10A7'},
      {value: '华台村', label: '10A8'},
      {value: '东浜头村', label: '10A9'},
      {value: '河山社区', label: '10A10'},
    ],
  },
  {
    label: '11',
    value: '乌镇镇',
    children: [
      {value: '白马墩村', label: '11A1'},
      {value: '分水墩村', label: '11A2'},
      {value: '碓坊桥村', label: '11A3'},
      {value: '浮澜桥村', label: '11A4'},
      {value: '陈庄村', label: '11A5'},
      {value: '虹桥村', label: '11A6'},
      {value: '南庄桥村', label: '11A7'},
      {value: '横港村', label: '11A8'},
      {value: '彭家村', label: '11A9'},
      {value: '陈家村', label: '11A10'},
      {value: '五星村', label: '11A11'},
      {value: '双塔村', label: '11A12'},
      {value: '颜家村', label: '11A13'},
      {value: '民合村', label: '11A14'},
      {value: '浙月村', label: '11A15'},
      {value: '新翁村', label: '11A16'},
      {value: '西浜村', label: '11A17'},
      {value: '元丰村', label: '11A18'},
      {value: '南王村', label: '11A19'},
      {value: '董家村', label: '11A20'},
      {value: '金牛村', label: '11A21'},
      {value: '正福村', label: '11A22'},
      {value: '杨园村', label: '11A23'},
      {value: '翔厚村', label: '11A24'},
      {value: '单桥村', label: '11A25'},
      {value: '皂林村', label: '11A26'},
      {value: '东苑社区', label: '11A27'},
      {value: '南宫社区', label: '11A28'},
      {value: '银杏社区', label: '11A29'},
      {value: '秀溪社区', label: '11A30'},
    ],
  },
  {
    label: '12',
    value: '石门镇',
    children: [
      {value: '叶新村', label: '12A1'},
      {value: '桂花村', label: '12A2'},
      {value: '颜井桥村', label: '12A3'},
      {value: '白马塘村', label: '12A4'},
      {value: '石门村', label: '12A5'},
      {value: '墅丰村', label: '12A6'},
      {value: '民丰村', label: '12A7'},
      {value: '民联村', label: '12A8'},
      {value: '殷家漾村', label: '12A9'},
      {value: '陆家庄村', label: '12A10'},
      {value: '春丽桥村', label: '12A11'},
      {value: '周墅塘村', label: '12A12'},
      {value: '郜墩村', label: '12A13'},
      {value: '东池村', label: '12A14'},
      {value: '安全村', label: '12A15'},
      {value: '羔羊村', label: '12A16'},
      {value: '二大埭村', label: '12A17'},
      {value: '崇安村', label: '12A18'},
      {value: '玉溪社区', label: '12A19'},
    ],
  },
]

export default data